### ISSUE TITLE
Support automatic downloads for Stockfish versions >= 16

### ISSUE THREAD

**Issue by jpenilla** [jpenilla/chesscraft#17]
Stockfish removed all old downloads from their site, which broke our auto downloader. The downloader has since been 'fixed' using archive.org for versions up to 15.1.

Starting with Stockfish 16, [GitHub Releases](https://github.com/official-stockfish/Stockfish/releases) is the official source for prebuilt binaries. We should add support for this somehow so that we can auto-download SF16 and new versions in the future.

The variety of binaries provided is different now as well, so this will probably require changes to the CPU feature detection; which needs to be changed anyways to support ARM CPUs (even though SF only provides x86-64 binaries for many platforms, these can often be used on aarch64 systems, for example with Apple's Rosetta). When implementing the new downloading logic it would also be a good time to properly support macOS; whether only for 16+ or also legacy versions.

**Comment by jpenilla** [comment]
"Fixed" with archive.org - still needs updates for Stockfish >=16 11ba65a587e92bd044449bba7549bbdc116d9d08

**Comment by jpenilla** [comment]
`https://files.stockfishchess.org/` seems to be back up...

**Comment by Olen** [comment]
Getting the assets for releases is pretty trivial using the github API:
https://docs.github.com/en/free-pro-team@latest/rest/releases/releases?apiVersion=2022-11-28#list-releases
You can use any github-token to authenticate. I just tested with both a "classic" and a "fine grained token" without any permissions, and I was able to retrieve the JSON-list of stockfish-releases (with all their assets).  So you should probably be able to distribute a token in the JAR without any dangerous implications.

## Classic token
![image](https://github.com/jpenilla/chesscraft/assets/203184/862c88e4-ee59-483f-bd95-9cbd9724b413)


## Fine grained token
![image](https://github.com/jpenilla/chesscraft/assets/203184/bcb77639-819e-4be5-b4ad-e3221d73a12d)

**Comment by jpenilla** [comment]
https://github.com/jpenilla/chesscraft/commit/f530c4ee8f73195acd9179cd0416c2248de1017d
