### ISSUE TITLE
removing a board leaves behind all it's floating text

### ISSUE THREAD

**Issue by x0rtrunks** [jpenilla/chesscraft#59]
I tried using this plugin and got it working, but when I tried to remove the test board, all of the floating text was left behind. While messing around I created 3 more boards and can't remove the rest of them either. I removed the plugin, but the text remains. 
![Screen Shot 2024-04-24 at 1 38 44 PM](https://github.com/jpenilla/chesscraft/assets/596160/5171cd36-99ae-47ab-be5d-d11ac589f516)

How do I get rid of this text in the air or on the ground or the pieces of paper on the ground?

**Comment by jpenilla** [comment]
what version are you using? this shouldn't happen on latest. you can use /kill to kill the text_displays

**Comment by x0rtrunks** [comment]
it was 0.4 probably 2 months ago. I'll try the 0.5 release and try /kill.
Thanks

**Comment by x0rtrunks** [comment]
/kill kills myself LOL
/kill text_displays gives No entity was found

I had used the commands to remove the boards initially, then I removed the plugin entirely. I'm not even sure I have a backup of the configs. I'll have to look.

**Comment by x0rtrunks** [comment]
/kill @e[type=minecraft:text_display] worked to get rid of the floating text, but now how do I get rid of the pieces of paper on the ground that were the placeholders for the chess pieces?

**Comment by jpenilla** [comment]
they are item_display or armor_stand

**Comment by x0rtrunks** [comment]
Thanks. item_display did it. 

I appreciate the support. I'll give 0.5 a try. My 6 y.o. is excited to play chess in minecraft.
